export const LOG_IN = '[AUTH] LOG_IN';
export const LOG_OUT = '[AUTH] LOG_OUT';
export const LOG_OUT_FINISHED = '[AUTH] LOG_OUT_FINISHED';
export const LOG_IN_FINISHED = '[AUTH] LOG_IN_FINISHED';
export const INIT_LOADER = '[AUTH] INIT_LOADER';
export const FINISH_LOADER = '[AUTH] FINISH_LOADER';
export const SIGN_UP = '[AUTH] SIGN_UP';
export const LOG_IN_SIGN_IN_FAILED = '[AUTH] LOG_IN_SIGN_IN_FAILED';
export const TRY_LOG_IN = '[AUTH] TRY_LOG_IN';
export const RESET_ERROR = '[AUTH] RESET_ERROR';
export const SEND_PASS_EMAIL = '[AUTH] SEND_PASS_EMAIL';
export const SEND_CONFIRMATION_EMAIL = '[AUTH] SEND_CONFIRMATION_EMAIL';

