"""empty message

Revision ID: 61187ffed059
Revises: 4387a768b7ab
Create Date: 2020-04-15 00:18:58.921987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61187ffed059'
down_revision = '4387a768b7ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('confirmation',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('expire_at', sa.Integer(), nullable=False),
    sa.Column('confirmed', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_confirmation_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_confirmation'))
    )
    op.alter_column('item', 'price',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('item', 'price',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=True)
    op.drop_table('confirmation')
    # ### end Alembic commands ###
