//STORES
export const FETCH_STORES = "[STORE] FETCH_STORES";
export const FETCH_STORES_SUCCESS = "[STORE] FETCH_STORES_SUCCESS";
export const FETCH_STORES_FAILED = "[STORE] FETCH_STORES_FAILED";

export const FETCH_OWN = "[STORE] FETCH_OWN";
export const FETCH_OWN_SUCCESS = "[STORE] FETCH_OWN_SUCCESS";
export const FETCH_OWN_FAILED = "[STORE] FETCH_OWN_FAILED";

export const FETCH_STORE = "[STORE] FETCH_STORE";
export const FETCH_STORE_SUCCESS = "[STORE] FETCH_STORE_SUCCESS";
export const FETCH_STORE_FAILED = "[STORE] FETCH_STORE_FAILED";

export const UPDATE_STORE = "[STORE] UPDATE_STORE";
export const UPDATE_STORE_SUCCESS = "[STORE] UPDATE_STORE_SUCCESS";
export const UPDATE_STORE_FAILED = "[STORE] UPDATE_STORE_FAILED";

export const SAVE_STORE = "[STORE] SAVE_STORE";
export const SAVE_STORE_SUCCESS = "[STORE] SAVE_STORE_SUCCESS";
export const SAVE_STORE_FAILED = "[STORE] SAVE_STORE_FAILED";

export const DELETE_STORE = "[STORE] DELETE_STORE";
export const DELETE_STORE_SUCCESS = "[STORE] DELETE_STORE_SUCCESS";
export const DELETE_STORE_FAILED = "[STORE] DELETE_STORE_FAILED";

export const SET_CURRENT_STORE = "[STORE] SET_CURRENT_STORE";

//Items
export const SAVE_ITEM = "[STORE] SAVE_ITEM";
export const SAVE_ITEM_SUCCESS = "[STORE] SAVE_ITEM_SUCCESS";
export const SAVE_ITEM_FAILED = "[STORE] SAVE_ITEM_FAILED";

export const UPDATE_ITEM = "[STORE] UPDATE_ITEM";
export const UPDATE_ITEM_SUCCESS = "[STORE] UPDATE_ITEM_SUCCESS";
export const UPDATE_ITEM_FAILED = "[STORE] UPDATE_ITEM_FAILED";

export const DELETE_ITEM = "[STORE] DELETE_ITEM";
export const DELETE_ITEM_SUCCESS = "[STORE] DELETE_ITEM_SUCCESS";
export const DELETE_ITEM_FAILED = "[STORE] DELETE_ITEM_FAILED";
