// GET_USER_INFO
export const GET_USER_INFO = "[ACCOUNT] GET_USER_INFO";
export const GET_USER_INFO_SUCCESS = "[ACCOUNT] GET_USER_INFO_SUCCESS";
export const GET_USER_INFO_FAILED = "[ACCOUNT] GET_USER_INFO_FAILED";

// CHANGE_NAME
export const CHANGE_NAME = "[ACCOUNT] CHANGE_NAME";
export const CHANGE_NAME_SUCCESS = "[ACCOUNT] CHANGE_NAME_SUCCESS";
export const CHANGE_NAME_FAILED = "[ACCOUNT] CHANGE_NAME_FAILED";

// CHANGE_EMAIL
export const CHANGE_EMAIL = "[ACCOUNT] CHANGE_EMAIL";
export const CHANGE_EMAIL_SUCCESS = "[ACCOUNT] CHANGE_EMAIL_SUCCESS";
export const CHANGE_EMAIL_FAILED = "[ACCOUNT] CHANGE_EMAIL_FAILED";

// CHANGE_PASSWORD
export const CHANGE_PASSWORD = "[ACCOUNT] CHANGE_PASSWORD";
export const CHANGE_PASSWORD_SUCCESS = "[ACCOUNT] CHANGE_PASSWORD_SUCCESS";
export const CHANGE_PASSWORD_FAILED = "[ACCOUNT] CHANGE_PASSWORD_FAILED";

// DELETE_ACCOUNT
export const DELETE_ACCOUNT = "[ACCOUNT] DELETE_ACCOUNT";
export const DELETE_ACCOUNT_SUCCESS = "[ACCOUNT] DELETE_ACCOUNT_SUCCESS";
export const DELETE_ACCOUNT_FAILED = "[ACCOUNT] DELETE_ACCOUNT_FAILED";

