// SIGN_IN
export const SIGN_IN = '[AUTH] SIGN_IN';
export const SIGN_IN_SUCCESS = '[AUTH] SIGN_IN_SUCCESS';
export const SIGN_IN_FAILED = '[AUTH] SIGN_IN_FAILED';

// SIGN_OUT
export const SIGN_OUT = '[AUTH] SIGN_OUT';
export const SIGN_OUT_SUCCESS = '[AUTH] SIGN_OUT_SUCCESS';
export const SIGN_OUT_FAILED = '[AUTH] SIGN_OUT_FAILED';

// SIGN_UP
export const SIGN_UP = '[AUTH] SIGN_UP';
export const SIGN_UP_SUCCESS = '[AUTH] SIGN_UP_SUCCESS';
export const SIGN_UP_FAILED = '[AUTH] SIGN_UP_FAILED';

// SEND_PASS_EMAIL
export const SEND_PASS_EMAIL = '[AUTH] SEND_PASS_EMAIL';
export const SEND_PASS_EMAIL_SUCCESS = '[AUTH] SEND_PASS_EMAIL_SUCCESS';
export const SEND_PASS_EMAIL_FAILED = '[AUTH] SEND_PASS_EMAIL_FAILED';

// SEND_CONFIRMATION_EMAIL
export const SEND_CONFIRMATION_EMAIL = '[AUTH] SEND_CONFIRMATION_EMAIL';
export const SEND_CONFIRMATION_EMAIL_SUCCESS = '[AUTH] SEND_CONFIRMATION_EMAIL_SUCCESS';
export const SEND_CONFIRMATION_EMAIL_FAILED = '[AUTH] SEND_CONFIRMATION_EMAIL_FAILED';

